### ISSUE TITLE
Implement Relaton-XSF for XMPP XEP specifications

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-xsf#1]
As per https://github.com/ietf-tools/bibxml-service/issues/302 .

**Comment by ronaldtse** [comment]
Thanks to the XMPP Foundation, the XEP bibliographic data is now under CC0 (https://github.com/xsf/xeps/pull/1220) which allows for redistribution.

We need to model its bibliographic data and distribute them under the [relaton-data-xsf](https://github.com/relaton/relaton-data-xsf) data repository.

**Comment by ronaldtse** [comment]
This ticket is now actionable.

**Comment by andrew2net** [comment]
@ronaldtse implemented. Use relaton-cli v1.15.5 and relaton v1.15.4
```sh
$ relaton fetch "XEP 0001"         
[relaton-xsf] (XEP 0001) fetching...
[relaton] Downloaded index from https://raw.githubusercontent.com/relaton/relaton-data-xsf/main/index-v1.zip
[relaton-xsf] (XEP 0001) found XEP 0001
<bibdata type="standard" schema-version="v1.2.3">
  <fetched>2023-07-19</fetched>
  ...
```

**Comment by ronaldtse** [comment]
Thank you @andrew2net !
